project:
  type: book
  output-dir: docs

book:
  title: "Econometrics"
  author: "Ferdian Fadly"
  date: "2/26/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - regression.qmd
    - ts.qmd
    - simultan.qmd
    - panelgmm.qmd
    - summary.qmd
    - references.qmd
  navbar:
   right: 
     - icon: file-earmark-pdf
       href: "https://drive.google.com/file/d/1EwRIytRmzaxlz6Q_JrMpVQVFSJWulTcT/view?usp=drive_link"  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true

editor: visual

