# About Me {.unnumbered}

## Education

### Master of Statistics

The Australian National University (ANU) 2021-2022

### Bachelor of Applied Statistics

Sekolah Tinggi Ilmu Statistik (STIS) 2007-2011

## Teaching Experience

### STAT7055 - Introductory Statistics For Business and Finance

The Australian National University (ANU) 2022

### STAT1008 - Quantitative Research Methods

The Australian National University (ANU) 2022

### MST3106 - Panel Data Analytics

Universitas Riau (UNRI) 2023

### EPSEM4B - Econometrics (On-going)

Universitas Muhammadiyah Riau (UMRI) 2024

## Working/Research Experience

### Statistician

BPS - Statistics Indonesia (2011 - present)

### Research Fellow

Lensa Garuda Nusantara (LGN) (2022 - present)

### Research Fellow

Mata Garuda Institute (MGI) (2020 - 2022)

### Committee of Department of Research

ANU Indonesian Student Association (ANUISA) (2021 - 2022)

## Disclaimer : This Module is currently under development. Please provide Feedback and Suggestions.
